### ISSUE TITLE
input change event not fired?

### ISSUE THREAD

**Issue by Lrochefort** [starikovs/alt-checkbox#4]
I tried this piece of code when I create my checkbox:

$("#someId input").altCheckbox({
    sizeClass: "big"
});
	
$("#someId input").on("change", function(){
    //do something here based on the input's state
});

Visually, all goes well, but no event is fired when alt-checkbox changes the property (see line 51 in jquery.alt-checkbox.js).

Am I doing something wrong? I think alt-checkbox should trigger the change event automatically.

Thanks,
<L/>

**Comment by nz-treasure** [comment]
It's because you are actually clicking on an <a> element that has been created by alt-checkbox. The real checkbox is actually hidden. You can do something like this instead:
$(".alt-checkbox").bind("click", function () { alert( $(this).next().prop('checked') ); });

**Comment by juddybuddy77** [comment]
$(".alt-checkbox").bind("click", function () { alert( $(this).next().prop('checked') ); }); worked for me. Thanks.

**Comment by starikovs** [comment]
Hello everybody,

I rewrited the code related to change event. I think now it works correctly.

Thanks for reporting,
Vacheslav
