### ISSUE TITLE
.alt-checkbox gets overwritten by websites a-styles

### ISSUE THREAD

**Issue by WulleBulle** [starikovs/alt-checkbox#6]
Hi,

thank you for this nice checkbox formatter.
I just found a little maybe not so important behavior.

For example...if the websites stylesheet formats the a-tag with a text-decoration: underline, the alt-checboxes are underlined because it uses .alt-checkbox instead of a.alt-checkbox.

I fixed that for me by adding a.alt-checbox to the css file.

    .alt-checbox,
    a.alt-checkbox {...}

Bye :)

**Comment by starikovs** [comment]
Hi, WulleBulle!

Now it fixed in master branch.
It fixed with `text-decoration: none !important`.

Thanks for reporting.
