### ISSUE TITLE
Original checkbox doesn't get updated

### ISSUE THREAD

**Issue by WulleBulle** [starikovs/alt-checkbox#7]
Hello,

first of all thank you for this nice plugin.
Unfortunately it seems that the original checkbox input doesn't get updated by the click event of the altCheckbox script if the original checkbox is checked by default.
But I've tried it in your example page and it is the same there.

I have a checkbox replaced by altCheckbox. The checkbox has a checked and is checked by default. So the altCheckbox is as well. But when I uncheck the altCheckbox, the original input is not updated. After submitting the form the value of the input[type=checkbox] is still the inputs value (1 in this case).

This is the original checkbox by default:

    <input type="checkbox" name="mycheckbox" value="1" autocomplete="off" checked />

The altCheckbox looks by default:

    <a href="#" class="alt-checkbox fa-check medium outline-unchecked checked"></a>

If I click the altCheckbox, the class "checked" is removed while the original checkbox stays "checked". After submitting the value of the form field is 1.

Hope this is clear. If not let me know please.

Thank you in advance.

**Comment by WulleBulle** [comment]
How ambrassing. I just found another field with same name, always having the value 1. Excuse me please. I will close it.

**Comment by WulleBulle** [comment]
Damn, sorry again. I closed the ticket but didn't see that the other field is in another template that has nothing to do with this issue. Sorry. I Reopen and hope you apologize it.

**Comment by starikovs** [comment]
Hello, WulleBulle!

I'm not sure about "value" attribute of checkbox.. It's better to use "checked" property to get its state on client. For example, `jQuery("#my-checkbox-id").prop("checked")`. Or if you want to get its state on the server side `isset($_POST['my-checkbox-name'])`, it's PHP but you can do it in any language.

Hope this will help :)

**Comment by WulleBulle** [comment]
Hello Vacheslav,

thank you very much. I've done it server sided and will closes this "issue" which isn't one at last.

Thank you again, keep up the good work.

Greetings
Wulle
